# SPDX-License-Identifier: GPL-2.0
# gsensor drivers

obj-$(CONFIG_PS_AL3006) 		+= ps_al3006.o
obj-$(CONFIG_PS_STK3171) 		+= ps_stk3171.o
obj-$(CONFIG_PS_AP321XX) 		+= ps_ap321xx.o
obj-$(CONFIG_PS_STK3332)		+= ps_stk3332.o
obj-$(CONFIG_PS_STK3410) 		+= ps_stk3410.o
obj-$(CONFIG_PS_EM3071X)		+= ps_em3071x.o
obj-$(CONFIG_PS_UCS14620)		+= ps_ucs14620.o
# [feature development] mspark, 24.08.21, Add Proximity Sensor (RPR-0521)
obj-$(CONFIG_PS_RPR0521)		+= ps_rpr0521.o
